# Generated by Django 3.2 on 2023-03-02 01:42

import django.contrib.auth.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230301_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, reviews.models.not_me_username_validator]),
        ),
    ]
