# Generated by Django 3.2 on 2023-03-02 07:36

import django.contrib.auth.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, reviews.models.not_me_username_validator, reviews.models.validate_username]),
        ),
    ]
